version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env  # ← References the .env in project root
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env  # ← Also uses the same .env file
    environment:
      - BACKEND_URL=http://backend:8000